---
title: "Reconstruction"
author: "Quan Gan"
date: "4/3/2022"
output: 
  html_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(investr)
library(tidyverse)
library(ggplot2)
library(boot)
library(knitr)
library(data.table)
library(Rmisc)
library(patchwork)
# model libraries
library(IsoplotR)
library(deming)
library(rstan)
library(pracma)
library(MASS)
library(quantreg)
```

## load data in
```{r}
data_low <- read_csv("./Data/Dataset_S1_Mar8.csv")
data_intermediate <- read_csv("./Data/Dataset_S2_Mar8.csv")
data_high <- read_csv("./Data/Dataset_S3_Mar8.csv")
```

## helper function
```{r}

TRpredict <- function(calData, 
                     targety,
                     targetyError,
                     nObs,
                     obCal){
  
    calData <<- calData
    obCal<<-obCal
    std <- function(i) sd(i)/sqrt(length(i))
    mod <- stats::nls(formula = D47  ~ a + b1*(10^6/(Temperature+273.15)^2),
                                data = calData, 
                                start = list(a = mean(obCal[,1]),b1 = mean(obCal[,2])),
                                lower = c(a = (mean(obCal[,1])-std(obCal[,1])*1.96),b1 = (mean(obCal[,2])-std(obCal[,2])*1.96)),
                                upper = c(a = (mean(obCal[,1])+std(obCal[,1])*1.96),b1 = (mean(obCal[,2])+std(obCal[,2])*1.96)),
                                algorithm = "port") 
    
    estimate <- investr::invest(mod, y0 = rnorm(nObs, mean=targety, sd=targetyError),
                                 interval = "percentile",  seed = 3,  nsim=1000,
                                 extendInt="yes", progress=F, 
                                 lower=-100,
                                 upper=100)
    
    
  
    preds <- cbind.data.frame(D47= targety, 
                            D47error=targetyError,
                            temp=estimate$estimate, 
                            se=estimate$se, 
                            lwr=estimate$lower, 
                            upr=estimate$upper
                            )
  
    return(preds)
}


fit_model <- function(seed, statistic, dataSet, formula, replicate){
  set.seed(seed)
  results <- boot(data = dataSet,
                  statistic = statistic,
                  R = replicate,
                  formula = formula)
  
  return (results$t)
}



```

### different model setup
```{r}
OLS_boot <- function(formula, data, indices){
  d <- data[indices, ]
  OLS <- lm(formula, d)
  return (c(coef(OLS)))
}

york_boot <- function(formula, data, indices){
  d <- data[indices, ]
  york_data <- cbind(d$Temperature, d$TempError, d$D47, d$D47error)
  fit_model <- york(york_data)
  return (c(fit_model$a['a'], fit_model$b['b']))
}

deming_boot <- function(formula, data, indices){
  d <- data[indices, ]
  fit_model <- deming(formula, data=d, xstd=abs(TempError), ystd=abs(D47error)) 
  return (c(fit_model$coefficients[1], fit_model$coefficients[2]))
}

ODR_boot <- function(formula, data, indices){
  d <- data[indices, ]
  fit_model <- odregress(d$Temperature, d$D47)
  return (c(fit_model$coef[2], fit_model$coef[1]))
}

QR_boot <- function(formula, data, indices){
  d <- data[indices, ]
  fit_model <- rq(formula, data=d)
  return (c(coef(fit_model)))
}

rlm_boot <- function(formula, data, indices){
  d <- data[indices, ]
  fit_model <- rlm(formula, data=d)
  return (c(coef(fit_model)))
}

TS_boot <- function(formula, data, indices){
  d <- data[indices, ]
  fit_model <- theilsen(formula, data=d)
  return (c(coef(fit_model)))
}

LSMC_fit <- function(data, seed){
  set.seed(seed)
  N <- nrow(data)           #Sample Size
  M <- 1000                 #Number of experiments/iterations
  
  ## Storage
  intercept_DT <- rep(0, M)
  slope_DT <- rep(0, M)

  ## begin Monte Carlo
  for (i in 1:M) {
    U_i = rnorm(N, 0, sqrt(abs(data$D47error)))
    x_i = rnorm(N, data$x_TRUE, sqrt(abs(data$TempError)))
    # Y_i = alpha_TRUE + beta_TRUE * x_i + U_i
    Y_i = rnorm(N, data$y_TRUE, sqrt(abs(data$D47error)))
    
    # Formulate data.table
    data_i = data.table(Y = Y_i, X = x_i)
    
    # Run regressions
    ols_i <- lm(data = data_i, Y ~ X)
    
    
    # Extract coefficient and save
    slope_DT[i] <- coef(ols_i)[2]
    intercept_DT[i] <- coef(ols_i)[1]
  }
  
  return (cbind(intercept_DT, slope_DT))
}

Bayesian_fit <- function(data, seed){
  rstan_options(auto_write = TRUE)
  stan_date <- list(N = nrow(data), 
                        Temperature = data$Temperature, 
                        Temperature_true = data$x_TRUE,
                        Temperature_error = abs(data$TempError),
                        D47 = data$D47,
                        D47_true = data$y_TRUE,
                        D47_error = abs(data$D47error))
  
  Bayesian_model <- stan(file = "./Baseline_models/stan/Bayesian_linear_model_with_error.stan", data = stan_date, iter = 1000, chains = 4, seed = seed)
  
  Bayesian_result <- rstan::extract(Bayesian_model)
  
  return(cbind(Bayesian_result$alpha, Bayesian_result$beta))
}


```

## Calculate coefficiences
```{r}
calCoef <- function(data){
  OLS_result <- fit_model(1234, OLS_boot, data, D47~Temperature, 1000)
  york_result <- fit_model(1234, york_boot, data, D47~Temperature, 1000)
  deming_result <- fit_model(1234, deming_boot, data, D47~Temperature, 1000)
  bayesian_resule <- Bayesian_fit(data, 1234)
  LSMC_result <- LSMC_fit(data_low, 1234)
  ODR_result <- fit_model(1234, ODR_boot, data, D47~Temperature, 1000)
  QR_result <- fit_model(1234, QR_boot, data, D47~Temperature, 1000)
  rlm_result <- fit_model(1234, rlm_boot, data, D47~Temperature, 1000)
  TS_result <- fit_model(1234, TS_boot, data, D47~Temperature, 1000)
  
  return(list(OLS = OLS_result, 
              york = york_result, 
              deming = deming_result,
              bayesian = bayesian_resule, 
              LSMC = LSMC_result, 
              ODR = ODR_result, 
              QR = QR_result, 
              RLM = rlm_result, 
              TS = TS_result))
}


```





## inversion predict

```{r}
reconstruct <- function(data, D47, D47Error, n , coeffi){
  OLS_recon <- TRpredict(data, D47, D47Error, n , coeffi[["OLS"]])
  print(OLS_recon)
  york_recon <- TRpredict(data, D47, D47Error, n , coeffi[["york"]])
  print(york_recon)
  deming_recon <- TRpredict(data, D47, D47Error, n , coeffi[["deming"]])
  print(deming_recon)
  bayesian_recon <- TRpredict(data, D47, D47Error, n , coeffi[["bayesian"]])
  print(bayesian_recon)
  LSMC_recon <- TRpredict(data, D47, D47Error, n , coeffi[["LSMC"]])
  print(LSMC_recon)
  ODR_recon <- TRpredict(data, D47, D47Error, n , coeffi[["ODR"]])
  print(ODR_recon)
  QR_recon <- TRpredict(data, D47, D47Error, n , coeffi[["QR"]])
  print(QR_recon)
  RLM_recon <- TRpredict(data, D47, D47Error, n , coeffi[["RLM"]])
  print(RLM_recon)
  TS_recon <- TRpredict(data, D47, D47Error, n , coeffi[["TS"]])
  print(TS_recon)
  
  modelName <- c("OLS", "York", "Deming", "bayesian", "LSMC","ODR", "Quantile", "Robust", "Theil-Sen")
  
  performances <- rbind(OLS_recon,
                        york_recon,
                        deming_recon,
                        bayesian_recon,
                        LSMC_recon,
                        ODR_recon,
                        QR_recon,
                        RLM_recon,
                        TS_recon)

  return (cbind(modelName, performances))
}

# rstan_options(auto_write = TRUE)
# stan_date <- list(N = nrow(data_low),
#                       Temperature = data_low$Temperature,
#                       Temperature_true = data_low$x_TRUE,
#                       Temperature_error = abs(data_low$TempError),
#                       D47 = data_low$D47,
#                       D47_true = data_low$y_TRUE,
#                       D47_error = abs(data_low$D47error),
#                       D47_new = rnorm(1000, 0.6, 0.05))
# 
# Bayesian_model <- stan(file = "./Bayesian_error_reconstruction.stan", data = stan_date, iter = 1000, chains = 4, seed = 123)
# 
# Bayesian_result <- rstan::extract(Bayesian_model)
# mean(Bayesian_result$TempPredict)

drawGraph <- function(data, miny, maxy) {
  graph <- data %>% 
    ggplot(aes(x = modelName, y = uncertainty, fill = modelName)) +
    geom_col() +
    geom_text(aes(label=round(uncertainty, 4)), position=position_dodge(width=0.9), vjust=-0.25) +
    coord_cartesian(ylim=c(miny, maxy)) +
    # labs(title = title,
    #      caption = caption) + 
    theme(plot.title = element_text(size=10))
  
  return(graph)
}


# expression(paste("Temperature reconstruction for D47 = 0.6%", ""[o]," error = 0.05%"[o] ," True Temperature = 60", ""^"o", "C")),
# paste("Using ", dataName," data set fits different models \n Predicting temperature from D47 and models' coefficients"))

```

### get the coefficient parameters
```{r}
coefficients_low <- calCoef(data_low)
coefficients_intermediate <- calCoef(data_intermediate)
coefficients_high <- calCoef(data_high)
```

## D47 = 0.6

```{r fig.align="center", echo = FALSE, fig.width = 12, fig.height= 14}

set.seed(123)
recon_6_error <- reconstruct(data_low, 0.6, 0.05, 1000, coefficients_low)
recon_6_error$uncertainty <- 60 - recon_6_error$temp
graph6_low <- drawGraph(recon_6_error,  
                    -max(abs(recon_6_error$uncertainty)),
                    max(abs(recon_6_error$uncertainty)))

set.seed(123)
recon_6_error <- reconstruct(data_intermediate, 0.6, 0.05, 1000, coefficients_intermediate)
recon_6_error$uncertainty <- 60 - recon_6_error$temp
graph6_intermediate <- drawGraph(recon_6_error,  
                    -max(abs(recon_6_error$uncertainty)),
                    max(abs(recon_6_error$uncertainty)))

set.seed(123)
recon_6_error <- reconstruct(data_high, 0.6, 0.05, 1000, coefficients_high)
recon_6_error$uncertainty <- 60 - recon_6_error$temp
graph6_high <- drawGraph(recon_6_error,  
                    -max(abs(recon_6_error$uncertainty)),
                    max(abs(recon_6_error$uncertainty)))

graph6_low / graph6_intermediate / graph6_high

```

## D47 = 0.7

```{r fig.align="center", echo = FALSE, fig.width = 12, fig.height= 14}

set.seed(123)
recon_7_error <- reconstruct(data_low, 0.7, 0.05, 1000, coefficients_low)
recon_7_error$uncertainty <- 19 - recon_7_error$temp
graph7_low <- drawGraph(recon_7_error,  
                    -max(abs(recon_7_error$uncertainty)),
                    max(abs(recon_7_error$uncertainty)))

set.seed(123)
recon_7_error <- reconstruct(data_intermediate, 0.7, 0.05, 1000, coefficients_intermediate)
recon_7_error$uncertainty <- 19 - recon_7_error$temp
graph7_intermediate <- drawGraph(recon_7_error,  
                    -max(abs(recon_7_error$uncertainty)),
                    max(abs(recon_7_error$uncertainty)))

set.seed(123)
recon_7_error <- reconstruct(data_high, 0.7, 0.05, 1000, coefficients_high)
recon_7_error$uncertainty <- 19 - recon_7_error$temp
graph7_high <- drawGraph(recon_7_error,  
                    -max(abs(recon_7_error$uncertainty)),
                    max(abs(recon_7_error$uncertainty)))

graph7_low / graph7_intermediate / graph7_high

```

## D47 = 0.8
```{r fig.align="center", echo = FALSE, fig.width = 12, fig.height= 14}

set.seed(123)
recon_8_error <- reconstruct(data_low, 0.8, 0.05, 1000, coefficients_low)
recon_8_error$uncertainty <- -9.8 - recon_8_error$temp
graph8_low <- drawGraph(recon_8_error,  
                    -max(abs(recon_8_error$uncertainty)),
                    max(abs(recon_8_error$uncertainty)))

set.seed(123)
recon_8_error <- reconstruct(data_intermediate, 0.8, 0.05, 1000, coefficients_intermediate)
recon_8_error$uncertainty <- -9.8 - recon_8_error$temp
graph8_intermediate <- drawGraph(recon_8_error,  
                    -max(abs(recon_8_error$uncertainty)),
                    max(abs(recon_8_error$uncertainty)))

set.seed(123)
recon_8_error <- reconstruct(data_high, 0.8, 0.05, 1000, coefficients_high)
recon_8_error$uncertainty <- -9.8 - recon_8_error$temp
graph8_high <- drawGraph(recon_8_error,  
                    -max(abs(recon_8_error$uncertainty)),
                    max(abs(recon_8_error$uncertainty)))

graph8_low / graph8_intermediate / graph8_high

```









