---
title: "TR_prediction"
author: "Quan Gan"
date: "4/19/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
source("Global.R")
```


## get the model coefficient
```{r}
getCals <- function(data, 
                    replicates, 
                    samples = NULL, 
                    D47error = "D47error", 
                    n.iter = 5000, 
                    priors = "Informative"){
  
  LMcals <<- simulateLM_measured(data, replicates = replicates, samples = samples, D47error = D47error)
  yorkcals <<- simulateYork_measured(data, replicates = replicates, samples = samples, D47error = D47error)
  demingcals <<- simulateDeming(data, replicates = replicates, samples = samples, D47error = D47error)
  bayeslincals <<- fitClumpedRegressions(data, n.iter = n.iter, priors = priors, samples = samples, D47error = D47error)
  LSMCcals <<- simulateLSMC_measured(data, replicates = replicates, samples = samples, D47error = D47error)
  ODRcals <<- simulateODR_measured(data, replicates = replicates, samples = samples, D47error = D47error)
  QRcals <<- simulateQR_measured(data, replicates = replicates, samples = samples, D47error = D47error)
  RLMcals <<- simulateRLM_measured(data, replicates = replicates, samples = samples, D47error = D47error)
  TScals <<- simulateTS_measured(data, replicates = replicates, samples = samples, D47error = D47error)
  
  list(LMcals = LMcals,
       yorkcals = yorkcals,
       demingcals = demingcals,
       bayeslincals = bayeslincals,
       LSMCcals = LSMCcals,
       ODRcals = ODRcals,
       QRcals = QRcals,
       RLMcals = RLMcals,
       TScals = TScals
       )
}
```

## Coefficient
```{r}
set.seed(3)
lowCoef <<- getCals(data_low, 1000)
intermediateCoef <<- getCals(data_intermediate, 1000)
highCoef <<- getCals(data_high, 1000)
```


##reconstruction
```{r}
calRec <- function(calData, recData, cals){

  do.call(rbind,lapply(1:nrow(recData), function(x){
                a <- predictTc(calData, targety=recData$D47[x], obCal=cals)
                b <- predictTc(calData, targety=recData$D47[x]+recData$D47error[x], obCal=cals)
                cbind.data.frame("D47"=recData$D47[x],"D47se"=recData$D47error[x], "Tc"=a$temp, "se"=a$temp-b$temp)
                }))
}

AllRec <- function(data, recData, cals){
  LMrc <- calRec(data, recData, cals$LMcals)
  yorkrc <- calRec(data, recData, cals$yorkcals)
  demingrc <- calRec(data, recData, cals$demingcals)
  BLM1calsMatrix <- cals$bayeslincals$BLM1_fit$BUGSoutput$sims.matrix
  BLM1cal <- cbind.data.frame(alpha = BLM1calsMatrix[,1],
                              beta = BLM1calsMatrix[,2])
  BLM_norc <-calRec(data, recData, BLM1cal)
  BLMrc <- BayesianPredictions(cals$bayeslincals, recData$D47, abs(recData$D47error), 1)
  names(BLMrc) <- c("D47", "D47se", "Tc", "se")
  LSMCrc <-calRec(data, recData, cals$LSMCcals)
  ODRrc <-calRec(data, recData, cals$ODRcals)
  QRrc <-calRec(data, recData, cals$QRcals)
  RLMrc <-calRec(data, recData, cals$RLMcals)
  TSrc <-calRec(data, recData, cals$TScals)
  
  rbind.data.frame(LMrc,
                   yorkrc,
                   demingrc,
                   BLM_norc,
                   BLMrc,
                   LSMCrc,
                   ODRrc,
                   QRrc,
                   RLMrc,
                   TSrc)
}


names = c("OLS",
          "york",
          "deming",
          "nonbayesian",
          "bayesian",
          "LSMC",
          "ODR",
          "QR",
          "RLM",
          "TS")

```

```{r, fig.align='center', fig.width=10, fig.height=11}
inverted <- function(D47, D47error, trueTemp){
  recData <- data.frame(D47 = D47,
                      D47error = D47error)

  lowResult <- AllRec(data_low, recData, lowCoef)
  lowResult$name = names
  lowResult$dataset <- rep("low_error", nrow(lowResult))
  lowResult$accuracy <- lowResult$Tc - trueTemp
  
  intermediateResult <- AllRec(data_intermediate, recData, intermediateCoef)
  intermediateResult$name = names
  intermediateResult$dataset <- rep("intermediate_error", nrow(intermediateResult))
  intermediateResult$accuracy <- intermediateResult$Tc - trueTemp
  
  highResult <- AllRec(data_high, recData, highCoef)
  highResult$name = names
  highResult$dataset <- rep("high_error", nrow(highResult))
  highResult$accuracy <- highResult$Tc - trueTemp
  
  rbind.data.frame(lowResult, intermediateResult, highResult)
}

```


```{r}
lowError_D47 <- inverted(0.6, 0.005, 60)
intermediateError_D47 <- inverted(0.6, 0.01, 60)
highError_D47 <- inverted(0.6, 0.02, 60)
```


```{r, fig.align='center', fig.width=8, fig.height=10}
rbind(lowError_D47, intermediateError_D47,highError_D47) %>% 
  ggplot(aes(x = as.factor(D47se), y = se, color = name),
         size=25) + 
  geom_line(aes(group = name),
            size=1,
             position = "identity") +
  geom_point() +
  facet_wrap(~factor(dataset,
                     levels = c("low_error", "intermediate_error", "high_error")), 
             ncol= 1,
             scales = "free") + 
  scale_colour_brewer(palette = "Paired") +
  labs(x = "D47 error",
       y = "Precision",
       color = "Model names",
       title = "High-temperature carbonate",
       subtitle = expression(paste("Targe D47=", "0.6%"["o"], "True Temperature =", "60"^"0", "C")))
```


```{r, fig.align='center', fig.width=8, fig.height=11}
rbind(lowError_D47, intermediateError_D47, highError_D47) %>% 
    dplyr::group_by(name, dataset) %>% 
    dplyr::summarise(model_accuracy = mean(accuracy)) %>% 
    ggplot(aes(x = name, y = model_accuracy, fill = name)) +
    geom_col() +
    geom_text(aes(label=round(model_accuracy, 4)),
              position=position_dodge(width=0.9), 
              vjust=-0.25) +
    scale_fill_brewer(palette = "Paired") +
    facet_wrap(~factor(dataset,
                     levels = c("low_error", "intermediate_error", "high_error")), 
               ncol= 1,
               scale = "free")  + 
    labs(x = "Model Names",
       y = "Accuracy",
       color = "Model names",
       title = "High-temperature carbonate",
       subtitle = expression(paste("Targe D47=", "0.6%"["o"], "True Temperature =", "60"^"0", "C")))
```

```{r}
lowError_D47 <- inverted(0.7, 0.005, 19)
intermediateError_D47 <- inverted(0.6, 0.01, 19)
highError_D47 <- inverted(0.7, 0.02, 19)
```


```{r, fig.align='center', fig.width=8, fig.height=10}
rbind(lowError_D47, intermediateError_D47,highError_D47) %>% 
  ggplot(aes(x = as.factor(D47se), y = se, color = name),
         size=25) + 
  geom_line(aes(group = name),
            size=1,
             position = "identity") +
  geom_point() +
  facet_wrap(~factor(dataset,
                     levels = c("low_error", "intermediate_error", "high_error")), 
             ncol= 1,
             scales = "free") + 
  scale_colour_brewer(palette = "Paired") +
  labs(x = "D47 error",
       y = "Precision",
       color = "Model names",
       title = "Intermediate-temperature carbonate",
       subtitle = expression(paste("Targe D47=", "0.7%"["o"], "True Temperature =", "19"^"0", "C")))
```

```{r, fig.align='center', fig.width=8, fig.height=11}
rbind(lowError_D47, intermediateError_D47,highError_D47) %>% 
    dplyr::group_by(name, dataset) %>% 
    dplyr::summarise(model_accuracy = mean(accuracy)) %>% 
    ggplot(aes(x = name, y = model_accuracy, fill = name)) +
    geom_col() +
    geom_text(aes(label=round(model_accuracy, 4)),
              position=position_dodge(width=0.9), 
              vjust=-0.25) +
    scale_fill_brewer(palette = "Paired") +
    facet_wrap(~factor(dataset,
                     levels = c("low_error", "intermediate_error", "high_error")), 
               ncol= 1,
               scale = "free") + 
    labs(x = "Model Names",
       y = "Accuracy",
       color = "Model names",
       title = "Intermediate-temperature carbonate",
       subtitle = expression(paste("Targe D47=", "0.7%"["o"], "True Temperature =", "19"^"0", "C")))
```

```{r}
lowError_D47 <- inverted(0.8, 0.005, -9.8)
intermediateError_D47 <- inverted(0.8, 0.01, -9.8)
highError_D47 <- inverted(0.8, 0.02, -9.8)
```


```{r, fig.align='center', fig.width=8, fig.height=10}
rbind(lowError_D47, intermediateError_D47,highError_D47) %>% 
  ggplot(aes(x = as.factor(D47se), y = se, color = name),
         size=25) + 
  geom_line(aes(group = name),
            size=1,
             position = "identity") +
  geom_point() +
  facet_wrap(~factor(dataset,
                     levels = c("low_error", "intermediate_error", "high_error")), 
             ncol= 1,
             scales = "free") + 
  scale_colour_brewer(palette = "Paired") +
  labs(x = "D47 error",
       y = "Precision",
       color = "Model names",
       title = "Low-temperature carbonate",
       subtitle = expression(paste("Targe D47=", "0.8%"["o"], "True Temperature =", "-9.8"^"0", "C")))
```

```{r, fig.align='center', fig.width=8, fig.height=12}
rbind(lowError_D47, intermediateError_D47,highError_D47) %>% 
    dplyr::group_by(name, dataset) %>% 
    dplyr::summarise(model_accuracy = mean(accuracy)) %>% 
    ggplot(aes(x = name, y = model_accuracy, fill = name)) +
    geom_col() +
    geom_text(aes(label=round(model_accuracy, 4)),
              position=position_dodge(width=0.9), 
              vjust=-0.25) +
    scale_fill_brewer(palette = "Paired") +
    facet_wrap(~factor(dataset,
                     levels = c("low_error", "intermediate_error", "high_error")), 
               ncol= 1,
               scale = "free") +
      labs(x = "Model Names",
       y = "Accuracy",
       color = "Model names",
       title = "Low-temperature carbonate",
       subtitle = expression(paste("Targe D47=", "0.8%"["o"], "True Temperature =", "-9.8"^"0", "C")))
```








