---
title: "brms"
author: "Quan Gan"
date: "2/27/2022"
output: 
  html_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(tidyverse)
library(knitr)
library(ggplot2)
library(brms)
```


## load data in
There are three data sets with low, intermediate, and high errors.
```{r}
data_low <- read_csv("../Data/Dataset_S1.csv")
data_intermediate <- read_csv("../Data/Dataset_S2.csv")
data_high <- read_csv("../Data/Dataset_S3.csv")
```

## brms model
Bayesian regression model with 'stan'

```{r}

## alpha ~ normal(0.231, 0.065)
## beta ~ normal(0.039, 0.004)
## sigma ~ gamma(0.001, 0.001)
bprior_no_error <- c(
  prior(normal(0.231, 0.065), class = Intercept),
  prior(normal(0.039, 0.004), class = b),
  prior(gamma(0.001, 0.001), class = sigma)
)

## without errors
bform_no_errors <- bf(D47 ~ Temperature + 1)

fit_no_error <- brm(bform_no_errors , data = data_low, seed=1234, iter = 2000, family = gaussian, prior = bprior_no_error)

fixef(fit_no_error)
```

```{r}

## with errors
bprior <- c(
  prior(normal(0, 0.001), class= sdme),
  prior(normal(0.231, 0.065), class = Intercept),
  prior(normal(0.039, 0.004), class = b),
  prior(gamma(0.001, 0.001), class = sigma)
)

bform <- bf(D47 | mi(abs(D47error)) ~ 1 + me(Temperature, abs(TempError)))

get_prior(bform, data = data_low, prior = bprior)

fit <- brm(bform , data = data_low, seed=1234, iter = 2000, warmup = 1000, family = gaussian, prior = bprior, save_mevars = TRUE)


fit
```

```{r}
data_low %>% 
  ggplot(aes(x = x_TRUE, y=y_TRUE))  +
  geom_point() +
  geom_abline(slope = 0.0369, intercept = 0.268, color = 'red') +
  geom_abline(slope = 0.70, intercept = 0.22, color = 'yellow') + 
  labs(title = "York model with the low error data") + 
  xlab("True Temperature") + 
  ylab("True D47")
```